name: msmpusher
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.0-10.0.dev <3.0.0"

dependencies:
  auto_route: ^3.2.4
  contacts_service: ^0.6.3
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  dropdown_button2: ^1.2.2
  equatable: ^2.0.3
  excel: ^2.0.0-null-safety-3
  file_picker: ^4.5.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_keyboard_visibility: ^5.2.0
  flutter_screenutil: ^5.4.0
  fluttertoast: ^8.0.9
  freezed_annotation: ^1.1.0
  get: ^4.6.1
  get_it: ^7.2.0
  google_fonts: ^2.3.1
  internet_connection_checker: ^0.0.1+3
  intl: ^0.17.0
  percent_indicator: ^4.0.0
  permission_handler: ^9.2.0
  persistent_bottom_nav_bar: ^4.0.2
  pin_code_fields: ^7.4.0
  provider: ^6.0.2
  shared_preferences: ^2.0.13
  status_change: ^2.0.0
  uuid_type: ^2.0.0

dev_dependencies:
  auto_route_generator: ^3.2.3
  build_runner: ^2.1.8
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/logos/
    - assets/icons/
    - assets/start/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Black.ttf
  #         weight: 900
  #       - asset: fonts/Roboto-Bold.ttf
  #         weight: 700
  #       - asset: fonts/Roboto-Medium.ttf
  #         weight: 500
  #       - asset: fonts/Roboto-Regular.ttf
  #         weight: 400
  #       - asset: fonts/Roboto-thin.ttf
  #         weight: 100
  #       - asset: fonts/Roboto-light.ttf
  #         weight: 300
  #   - family: Pacifico
  #     fonts:
  #       - asset: fonts/Pacifico-Regular.ttf
  #         weight: 400
  #   - family: DMSans
  #     fonts:
  #       - asset: fonts/DMSans-Bold.ttf
  #         weight: 700
  #       - asset: fonts/DMSans-Medium.ttf
  #         weight: 500
  #       - asset: fonts/DMSans-Regular.ttf
  #         weight: 400
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
